spring.application.name=MyQuizzApp

spring.datasource.url = jdbc:postgresql://localhost:5432/Quizzit
spring.datasource.driver-class-name = org.postgresql.Driver
spring.datasource.username =postgres
spring.datasource.password=root


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

jwt.secret=46ab061d9d5bfe583413e22a017bcf95fc121774f2e66792949834f84f5f5eb67b2ebac8df2b375a3eb69254d638f767b98dffbe1181dbce311f98616dc5f5ee
jwt.expirationMs=86400000





